title: params-site
type: fragment
steps:
   - store:
        siteTimeout: 5000
        siteBaseUrl: https://automate.website
        siteAppUrl: ${siteBaseUrl}/app
        dataCurrentSshKey: Secr3t
        siteAppSelectorContainerHeader: div[ui-view=navbar]
        siteAppSelectorControlGotoAccount: ${siteAppSelectorContainerHeader} a[ui-sref="account"]
        siteSelectorContainerMain: div.container-main
        siteSelectorControlGotoProjects: ${siteAppSelectorContainerHeader} a[ui-sref="projects"]
        siteSelectorControlNavigateToPage: ${siteAppSelectorContainerHeader} h1 a.navbar-header-animation