title: goto-scenario-edit-page
type: fragment
steps:
    - click:
        parent:
          selector: ${scenariosPageSelectorScenarioContainer}
          text: ${dataCurrentScenarioTitle}
        selector: ${scenariosPageScenarioContainerSelectorDropdownControl}
    - click:
        selector: ${scenariosPageSelectorDropdownControlElements}
        text: ${scenariosPageControlTextEditScenario}
    - include: ensure-at-scenario-edit-page
