title: params
type: fragment
steps:
   - include: params-site
   - include: params-login-page
   - include: params-projects-page
   - include: params-account-page
   - include: params-register-page
   - include: params-change-password-page
   - include: params-user
         
