title: params-site
type: fragment
steps:
   - store:
        siteTimeout: 5000
   - store:
        siteBaseUrl: https://automate.website
   - store:
        siteAppUrl: ${siteBaseUrl}/app
   - store:
        dataCurrentScenarioTitle: New scenario
   - store:
        dataCurrentSshKey: Secr3t
   - store:
        siteAppSelectorContainerHeader: div[ui-view=navbar]
   - store:
        siteAppSelectorControlGotoAccount: ${siteAppSelectorContainerHeader} a[ui-sref="account"]
   - store:
        siteSelectorContainerMain: div.container-main
   - store:
        siteSelectorControlGotoProjects: ${siteAppSelectorContainerHeader} a[ui-sref="projects"]
   - store: 
        siteSelectorControlNavigateToPage: ${siteAppSelectorContainerHeader} h1 a.navbar-header-animation